allowBuilds:
  esbuild: true
  sharp: true
  workerd: false
minimumReleaseAgeExclude:
  - prettier@3.9.8
  - astro@7.3.5
  - prettier-plugin-astro@1.1.0
  - "@astrojs/internal-helpers@0.11.0"
  - "@astrojs/markdown-satteri@0.4.2"
  - "@bruits/satteri-darwin-arm64@0.10.5"
  - "@bruits/satteri-darwin-x64@0.10.5"
  - "@bruits/satteri-linux-arm64-gnu@0.10.5"
  - "@bruits/satteri-linux-arm64-musl@0.10.5"
  - "@bruits/satteri-linux-x64-gnu@0.10.5"
  - "@bruits/satteri-linux-x64-musl@0.10.5"
  - "@bruits/satteri-wasm32-wasi@0.10.5"
  - "@bruits/satteri-win32-arm64-msvc@0.10.5"
  - "@bruits/satteri-win32-x64-msvc@0.10.5"
  - wrangler@4.139.0
  - miniflare@5.20260923.0-alpha
  - satteri@0.10.5
  - workerd@1.20260921.1
  - "@cloudflare/unenv-preset@2.16.2"
  - "@cloudflare/workerd-darwin-64@1.20260921.1"
  - "@cloudflare/workerd-darwin-arm64@1.20260921.1"
  - "@cloudflare/workerd-linux-64@1.20260921.1"
  - "@cloudflare/workerd-linux-arm64@1.20260921.1"
  - "@cloudflare/workerd-windows-64@1.20260921.1"
