name = "fuckxter"
main = "worker/index.ts"
compatibility_date = "2026-09-08"

[placement]
mode = "smart"

[cache]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/", "/messages", "/messages/*", "/notice", "/post/*", "/user/*/followers", "/user/*/following"]

[observability]
enabled = true

[images]
binding = "IMAGES"
remote = true

[vars]
FUCKXTER_ORIGINS = "https://api.fuckxter.site,https://fuckxter.site,https://www.fuckxter.site"

[[routes]]
pattern = "fuckxter.site"
custom_domain = true

[[routes]]
pattern = "www.fuckxter.site"
custom_domain = true

[[routes]]
pattern = "api.fuckxter.site"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "fuckxter"
database_id = "6c654dd2-9ac1-4028-99d0-ee268874c498"
migrations_dir = "worker/databases"

[[r2_buckets]]
binding = "MEDIA_CACHE"
bucket_name = "fuckxter"

[[kv_namespaces]]
binding = "KV"
id = "04ae5aae580845bc9b923315aefab1fc"

[[queues.producers]]
binding = "JOBS"
queue = "fuckxchat"

[[queues.consumers]]
queue = "fuckxchat"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

[triggers]
crons = ["23 4 * * *"]
