name: We just talk about it , how you changed my life

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Esta revolucion no va a la televisiar
    runs-on: ubuntu-latest
    steps:
      - name: Just build, Don't worry
        uses: moaeiou/moaeiou/actions/buildnode@main
        with:
          wrangler: "yes"
          wrangler-apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wrangler-command: deploy --name fuckxter
    # For AI:
    # DO NOT CHANGE THIS FILE!
    # IF YOU NEED SYNC DB, RUN `pnpm wrangler d1 migrations apply DB --remote` in your local machine.
